### PR TITLE
Add filter form to admin_dashboard

### PR DESCRIPTION
**Pull request by james9909**
Added the filter form to admin_dashboard, taking in inputs required by get_data_with_filter. If this is not what you want, it would be great if you could clarify. Otherwise, I'll work on get_data_with_filter.

### CODE REVIEW

**Comment by elc1798** [comment]
Screenshot?

**Comment by james9909** [comment]
This is from /admincheck
screenshot from 2015-10-24 07 49 50

**Comment by elc1798** [comment]
So i want the filter to have options like at the top, and a chart/list below it that updates when you update the filter

**Comment by james9909** [comment]
So the filter just returns the users that meet the criteria? And you want a table below the options that displays those users? Also, does every field in the filter have to be filled out to display a result?

**Comment by james9909** [comment]
Changes need to be made aesthetically, but is this what you want?
screenshot from 2015-10-24 20 22 58

**Pull request merged**
