### PR TITLE
Limit query results to 1

### PR DESCRIPTION
**Pull request by james9909**
Prevents the breaking of several functions, should an sql query return multiple items, like over [here](https://github.com/elc1798/teammanager.py/blob/master/userdb.py#L139).

### CODE REVIEW

**Comment by elc1798** [comment]
The len(result) == 1 should take care of that... unless it's something I'm not aware of? Does the program crash or does it have unexpected behavior?

**Comment by james9909** [comment]
Upon checking to see if an admin or user exists, if the query returns multiple users, or duplicates, then len(result)  == 1 will return false and will result in a user/admin being considered non-existant. Same for checking if an id exists.

**Comment by elc1798** [comment]
But the query _shouldn't_ return multiple users. If it does, clearly there has been tampering. The system admin should solve that.

**Comment by elc1798** [comment]
You should write a cleanup function to remove duplicate entries :+1:

**Comment by james9909** [comment]
The code only breaks if there are multiple users with the same id or something, so they don't necessarily have to be duplicates. 

I'll add a check for a pre-existing user in adduser though.

**Pull request closed without merging**
